name: Skulls
version: plugin-version
api-version: 1.13
main: ca.tweetzy.skulls.Skulls
description: A collection of 20K+ custom heads
authors: [Kiran Hart]
depend: [Vault]
softdepend: [PlayerPoints, Reserve]

commands:
  skulls:
    description: Main command for the skulls plugin
    default: true
    usage: /skulls

